version: 2

sources:
  - name: olist
    database: OLIST_ECOMMERCE
    schema: PUBLIC
    tables:
      - name: orders
      - name: customers
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: geolocation
      - name: product_category_translation